ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS ai_model VARCHAR(255) DEFAULT 'llama-3.3-70b-versatile';
ALTER TABLE users ADD COLUMN IF NOT EXISTS ai_language VARCHAR(50) DEFAULT 'en-US';
ALTER TABLE users ADD COLUMN IF NOT EXISTS ai_voice VARCHAR(255) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_guest BOOLEAN DEFAULT FALSE;
